[server]
    AppMode = "debug"
    HttpPort = ":3000"
    JwtKey = "key"

[database]
    DB = "mysql"
    DBHost = "192.168.197.125"
    DBPort = 3306
    DBUser = "client"
    DBPassWord = "asdjkl"
    DBName = ""

