[server]
    AppMode = "debug"
    HttpPort = ":3001"
    JwtKey = "mykey"

[database]
    DB = "mysql"
    DBHost = "192.168.197.133"
    DBPort = 3306
    DBUser = "djn"
    DBPassWord = "asdjkl"
    DBName = "vote"

