CREATE DATABASE IF NOT EXISTS vote;

USE vote;

CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL,
    name VARCHAR(30),
    password VARCHAR(30),
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP,
);