// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.2
// source: qa.proto

package qa

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QaClient is the client API for Qa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QaClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type qaClient struct {
	cc grpc.ClientConnInterface
}

func NewQaClient(cc grpc.ClientConnInterface) QaClient {
	return &qaClient{cc}
}

func (c *qaClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/qa.Qa/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QaServer is the server API for Qa service.
// All implementations must embed UnimplementedQaServer
// for forward compatibility
type QaServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedQaServer()
}

// UnimplementedQaServer must be embedded to have forward compatible implementations.
type UnimplementedQaServer struct {
}

func (UnimplementedQaServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedQaServer) mustEmbedUnimplementedQaServer() {}

// UnsafeQaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QaServer will
// result in compilation errors.
type UnsafeQaServer interface {
	mustEmbedUnimplementedQaServer()
}

func RegisterQaServer(s grpc.ServiceRegistrar, srv QaServer) {
	s.RegisterService(&Qa_ServiceDesc, srv)
}

func _Qa_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QaServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qa.Qa/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QaServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Qa_ServiceDesc is the grpc.ServiceDesc for Qa service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Qa_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qa.Qa",
	HandlerType: (*QaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Qa_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qa.proto",
}
